version: '3'
services: 
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules   #  internal directory should not be updated by external same directory
            - .:/app
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules   #  internal directory should not be updated by external same directory
            - .:/app
        command: ["npm","run","test"]